# Generated by Django 4.2.7 on 2023-11-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H_Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotin', models.CharField(max_length=60)),
                ('arab', models.CharField(max_length=60)),
                ('haqida', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='H_Qismlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotin', models.CharField(max_length=100)),
                ('arab', models.CharField(max_length=100)),
                ('dan', models.IntegerField(default=0)),
                ('gacha', models.IntegerField(default=1)),
                ('kitobdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.h_kitoblar')),
            ],
        ),
        migrations.CreateModel(
            name='Q_Parchalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotin', models.CharField(max_length=100)),
                ('arab', models.CharField(max_length=100)),
                ('qismdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.h_qismlar')),
            ],
        ),
        migrations.CreateModel(
            name='V_Hadislar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotin', models.CharField(max_length=2000)),
                ('arab', models.CharField(max_length=2000)),
                ('toifa', models.CharField(default='Sahih', max_length=100)),
                ('tomonidan', models.CharField(default='by Someone', max_length=100)),
                ('kitobda', models.CharField(default='1 qism 4 bet 3 hadis', max_length=100)),
                ('parchadan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.q_parchalar')),
            ],
        ),
    ]
